Importing libraries

In [1]:
import os
import pandas as pd
import numpy as np
from tqdm import tqdm
import csv

In [5]:
# names = ["dennis","justin","kenneth","kenneth_brille","liza","liza_brille","miriam", 
#          "steffen", "adham", "vincent"]
root = os.getcwd()
image_folder = r"C:\Users\ASUS\datasets\image"
faces_folder = r"C:\Users\ASUS\datasets\cleaned-face"
names = list(os.listdir(faces_folder))
print(names)

['adham', 'dennis', 'justin', 'kenneth', 'kenneth_brille', 'liza', 'liza_brille', 'miriam', 'steffen', 'vincent']

Buat another column utk numerical value. End csv akan ada 3 column (path,name,id)

Label mapping

In [6]:
# Code to obtain label mapping
names_dict = {}
for id,name in enumerate(names):
    names_dict[id] = name

print(names_dict)

{0: 'adham', 1: 'dennis', 2: 'justin', 3: 'kenneth', 4: 'kenneth_brille', 5: 'liza', 6: 'liza_brille', 7: 'miriam', 8: 'steffen', 9: 'vincent'}

Creating dataframe by row

In [7]:
def row_generator(folder_list,names_dict):

    for folder in folder_list:
        for id,name in names_dict.items():
            sub_dir = os.path.join(folder,name)
            if os.path.exists(sub_dir):
                for filename in os.listdir(sub_dir):
                    file_path = os.path.join(sub_dir,filename)
                    yield file_path,name,id

row_gen = row_generator([faces_folder],names_dict)

image_counter = 0
try:
    while True:
        # Attempt to get the next item
        next_item = next(row_gen)
        image_counter += 1
        #print(next_item)
except StopIteration:
    print(f"End of iterator reached with {image_counter} images.")

End of iterator reached with 4662 images.

Creating dataframe by column

In [8]:
# Specify the path of the CSV file
# csv_file_path = os.path.join(root, 'datasets/label.csv')
csv_file_path = os.path.join(r'C:\Users\ASUS\datasets', 'face_label_id.csv')

# Open the CSV file in write mode
with open(csv_file_path, 'w', newline='') as csv_file:
    # Create a CSV writer
    csv_writer = csv.writer(csv_file)

    # Write the header to the CSV file
    csv_writer.writerow(['filepath', 'label', 'id'])

    # Iterate over the rows generated by 'row_generator'
    row_gen = row_generator([faces_folder], names_dict)
    for item in tqdm(row_gen):
        # Write each row to the CSV file
        csv_writer.writerow([item[0], item[1], item[2]])

4662it [00:00, 172679.18it/s]

Preprocessing for Model

In [9]:
data_df = pd.read_csv(r"C:\Users\ASUS\datasets\face_label_id.csv")
data_df

                                               filepath    label  id
0     C:\Users\ASUS\datasets\cleaned-face\adham\0000...    adham   0
1     C:\Users\ASUS\datasets\cleaned-face\adham\0000...    adham   0
2     C:\Users\ASUS\datasets\cleaned-face\adham\0000...    adham   0
3     C:\Users\ASUS\datasets\cleaned-face\adham\0000...    adham   0
4     C:\Users\ASUS\datasets\cleaned-face\adham\0000...    adham   0
...                                                 ...      ...  ..
4657  C:\Users\ASUS\datasets\cleaned-face\vincent\00...  vincent   9
4658  C:\Users\ASUS\datasets\cleaned-face\vincent\00...  vincent   9
4659  C:\Users\ASUS\datasets\cleaned-face\vincent\00...  vincent   9
4660  C:\Users\ASUS\datasets\cleaned-face\vincent\00...  vincent   9
4661  C:\Users\ASUS\datasets\cleaned-face\vincent\00...  vincent   9

[4662 rows x 3 columns]

One-Hot Encoding

In [10]:
data_df_encoded = pd.get_dummies(data_df,columns=["label"],dtype=float)
data_df_encoded

,filepath,id,label_adham,label_dennis,label_justin,label_kenneth,label_kenneth_brille,label_liza,label_liza_brille,label_miriam,label_steffen,label_vincent
0,C:\Users\ASUS\datasets\cleaned-face\adham\0000...,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,C:\Users\ASUS\datasets\cleaned-face\adham\0000...,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,C:\Users\ASUS\datasets\cleaned-face\adham\0000...,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,C:\Users\ASUS\datasets\cleaned-face\adham\0000...,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,C:\Users\ASUS\datasets\cleaned-face\adham\0000...,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4657,C:\Users\ASUS\datasets\cleaned-face\vincent\00...,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4658,C:\Users\ASUS\datasets\cleaned-face\vincent\00...,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4659,C:\Users\ASUS\datasets\cleaned-face\vincent\00...,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4660,C:\Users\ASUS\datasets\cleaned-face\vincent\00...,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4661,C:\Users\ASUS\datasets\cleaned-face\vincent\00...,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [11]:
data_df_encoded = data_df_encoded.drop(["id"],axis=1)
data_df_encoded

,filepath,label_adham,label_dennis,label_justin,label_kenneth,label_kenneth_brille,label_liza,label_liza_brille,label_miriam,label_steffen,label_vincent
0,C:\Users\ASUS\datasets\cleaned-face\adham\0000...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,C:\Users\ASUS\datasets\cleaned-face\adham\0000...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,C:\Users\ASUS\datasets\cleaned-face\adham\0000...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,C:\Users\ASUS\datasets\cleaned-face\adham\0000...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,C:\Users\ASUS\datasets\cleaned-face\adham\0000...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
4657,C:\Users\ASUS\datasets\cleaned-face\vincent\00...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4658,C:\Users\ASUS\datasets\cleaned-face\vincent\00...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4659,C:\Users\ASUS\datasets\cleaned-face\vincent\00...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4660,C:\Users\ASUS\datasets\cleaned-face\vincent\00...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4661,C:\Users\ASUS\datasets\cleaned-face\vincent\00...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [12]:
data_df_encoded["label"] = data_df["label"]

In [13]:
data_df_encoded

,filepath,label_adham,label_dennis,label_justin,label_kenneth,label_kenneth_brille,label_liza,label_liza_brille,label_miriam,label_steffen,label_vincent,label
0,C:\Users\ASUS\datasets\cleaned-face\adham\0000...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,adham
1,C:\Users\ASUS\datasets\cleaned-face\adham\0000...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,adham
2,C:\Users\ASUS\datasets\cleaned-face\adham\0000...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,adham
3,C:\Users\ASUS\datasets\cleaned-face\adham\0000...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,adham
4,C:\Users\ASUS\datasets\cleaned-face\adham\0000...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,adham
...,...,...,...,...,...,...,...,...,...,...,...,...
4657,C:\Users\ASUS\datasets\cleaned-face\vincent\00...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,vincent
4658,C:\Users\ASUS\datasets\cleaned-face\vincent\00...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,vincent
4659,C:\Users\ASUS\datasets\cleaned-face\vincent\00...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,vincent
4660,C:\Users\ASUS\datasets\cleaned-face\vincent\00...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,vincent
4661,C:\Users\ASUS\datasets\cleaned-face\vincent\00...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,vincent

In [8]:
data_df_encoded.to_csv(r"C:\Users\ASUS\datasets\face_label_encoded.csv")